### ISSUE TITLE
音乐列表中任选一首歌曲点击播放，偶尔出现两次该歌曲播放成功提示的弹窗。

### ISSUE THREAD

**Issue by hebiancao** [xiaoconghu/app-music-server#2]
<img width="960" alt="微信图片_20200321214938" src="https://user-images.githubusercontent.com/22684512/77227865-2102a080-6bbe-11ea-92ac-362861754182.png">

**Comment by xiaoconghu** [comment]
已修复
退出登录之后播放歌曲的订阅流没有销毁
